name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025
    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Add nuget to PATH
        uses: nuget/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f # v1.2.0

      - name: Install SignTool
        run: |
          dotnet tool install --tool-path . --prerelease sign

      - name: Restore NuGet packages
        run: |
          nuget restore IceBuilder.sln

      - name: Build Extension
        run: |
          MSBuild IceBuilder.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Sign VSIX Package
        if: env.AZURE_TENANT_ID != '' && env.AZURE_CLIENT_ID != '' && env.AZURE_CLIENT_SECRET != ''
        run: |
          .\sign.exe code trusted-signing ".\IceBuilder\bin\Release\IceBuilder.vsix" `
            --trusted-signing-endpoint https://eus.codesigning.azure.net/ `
            --timestamp-url http://timestamp.acs.microsoft.com `
            --trusted-signing-account zeroc `
            --trusted-signing-certificate-profile zeroc-ice `
            --azure-key-vault-tenant-id ${{ env.AZURE_TENANT_ID }} `
            --azure-key-vault-client-id ${{ env.AZURE_CLIENT_ID }} `
            --azure-key-vault-client-secret ${{ env.AZURE_CLIENT_SECRET }}

      - name: Upload Extension
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: IceBuilder
          path: |
            ./IceBuilder/bin/Release/*.vsix
